name: DeathCounter
version: 1.20.1
main: org.eu.deathcounter.DeathCounter
api-version: '1.20'
depend: [ClansLite]
commands:
  mortes:
    description: Mostra quantas mortes você tem.
    usage: /mortes
  tier:
    description: Mostra quem matou mais amiguinhos.
    usage: /tier
  setKill:
    usage: /setKill
  tierClans:
    usage: /tierClans